services:
  - type: web
    name: fitness-tracker-backend
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node app/handleStripe/handleBackend.js'
    envVars:
      - key: EXPO_OPENAI_PROJECT_API_KEY
        value: sk-proj-V7StkAKcaYwk4rBz51F9T3BlbkFJVVdF3OGCTMtAK7i81pTG
      - key: EXPO_OPENAI_ASSISTANCE_NUTRITIONIST
        value: asst_16SFcbwuPU721E6Iz6TVybbD
      - key: EXPO_OPENAI_GPT_PAT
        value: 50168f0b50684ef29f9d5c774f7833cd
      - key: EXPO_EDAMAM_APP_ID
        value: 90e2036b
      - key: EXPO_EDAMAM_APP_KEY
        value: b1e82289782395cb48b50b4b11520754
      - key: EXPO_HUGGINGFACE_API
        value: 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 
      - key: EXPO_STRIPE_SECRET_KEY
        value: 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
      - key: EXPO_STRIPE_PUBLISHABLE_KEY
        value: pk_live_51QVygSBQgjh8yS4RaETuRan0FbyEXul8jW5nZ3hBgifdl569WcuEFVf13gtO4CJljkzTictxrijHJvAplHuqvOow00QoyahQqQ
      - key: EXPO_FIREBASE_API_KEY
        value: AIzaSyCU2y_-Elwo74ZyKy8CjQytK-BedpsX-o0
      - key: EXPO_FIREBASE_AUTH_DOMAIN
        value: todo-mobile-app-3dcbc.firebaseapp.com
      - key: EXPO_FIREBASE_PROJECT_ID
        value: todo-mobile-app-3dcbc
      - key: EXPO_FIREBASE_STORAGE_BUCKET
        value: todo-mobile-app-3dcbc.appspot.com
      - key: EXPO_FIREBASE_MESSAGING_SENDER_ID
        value: 418018705359
      - key: EXPO_FIREBASE_APP_ID
        value: 1:418018705359:web:45d6427d74cd12ec471cba
      - key: EXPO_FIREBASE_MEASUREMENT_ID
        value: G-L8LBR0BEZ4