services:
  - type: web
    name: fitness-tracker-backend
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node app/handleStripe/handleBackend.js'
    envVars:
      - key: OPENAI_PROJECT_API_KEY
        value: sk-proj-V7StkAKcaYwk4rBz51F9T3BlbkFJVVdF3OGCTMtAK7i81pTG
      - key: OPENAI_ASSISTANCE_NUTRITIONIST
        value: asst_16SFcbwuPU721E6Iz6TVybbD
      - key: EDAMAM_APP_ID
        value: 90e2036b
      - key: EDAMAM_APP_KEY
        value: b1e82289782395cb48b50b4b11520754
      - key: HUGGINGFACE_API
        value: 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 
      - key: STRIPE_SECRET_KEY
        value: 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
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_live_51QVygSBQgjh8yS4RaETuRan0FbyEXul8jW5nZ3hBgifdl569WcuEFVf13gtO4CJljkzTictxrijHJvAplHuqvOow00QoyahQqQ